name: gn-hel

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */20 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Fetch new content
      run: |
        curl -s https://erjns.clever.college > lol

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add lol
        git commit -m "asd" || echo "asd"
        git push
